name: pneumonitis-ml
channels:
  - conda-forge
dependencies:
  # core
  - python =3.11
  - numpy  >=1.26
  - pandas >=2.2
  - scipy  >=1.12
  - scikit-learn >=1.4
  - statsmodels >=0.14

  # notebooks & plotting
  - jupyterlab
  - ipykernel
  - matplotlib
  - seaborn

  - imbalanced-learn
  - tqdm
  - pytest

  # pin a compiler toolchain so that binary wheels stay consistent
  - pip